<a href="https://colab.research.google.com/github/junaid537/Assig2WebTech/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
!nvidia-smi

Tue Feb  4 05:42:20 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   62C    P8             11W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [5]:
!nvidia-smi

Tue Feb  4 05:42:21 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   62C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [6]:
import torch as tor

In [7]:
tor.__version__

'2.5.1+cu124'

In [9]:
v=tor.tensor([2,3,4,5,6])
v
print(v.ndim)
print(v)

1
tensor([2, 3, 4, 5, 6])


In [10]:
matrix=tor.tensor([[1,2,3],[5,6,7]])

In [11]:
print(matrix.ndim)
print(matrix.shape)

2
torch.Size([2, 3])


In [12]:
rand_tensor= tor.randn(3,4)
rand_tensor

tensor([[-1.3167, -0.1378,  0.3963,  0.8873],
        [-0.0916, -0.1633, -1.0128, -0.4905],
        [-0.7136,  1.3908, -0.8001, -3.0335]])

In [13]:
zeros_a = tor.zeros(3,4)
zeros_a

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [14]:
#range
one_to_ten = tor.arange( start=1,end=11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
#tensors like
ten_zeros = tor.zeros_like(input = one_to_ten )
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
#Check for GPU Access with Pytorch
tor.cuda.is_available()

True

In [17]:
#By default tensors created on CPU
a = tor.tensor([1,2,3])
print(a, a.device)

tensor([1, 2, 3]) cpu
